services:
  server:
    build:
      context: .
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    expose:
      - 5432
    healthcheck:
      test: pg_isready -U ${PG_USER} -d ${PG_DATABASE}
      interval: 5s
      timeout: 5s
      retries: 3
volumes:
  db-data:
